# -*- coding: utf-8 -*-
"""FitScore.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Cly0c4yWJHNSMDxilUIqF0g5OY4mpkj

#**Titan Hackathon** Code of team (**SpamBytes**)

###Code for *Data Cleaning*
"""

import pandas as pd

import numpy as np

"""####Upload Dataset from files"""

from google.colab import files
uploaded = files.upload()

"""### Dataset display"""

data = pd.read_csv("person2.csv")
data.head(5)

df = data.copy()

"""##Name File using DataFrame of Pandas Library"""

#Create list of all coloumn Value to calculate on them
Weight = df['Weight'].values
Height = df['Height'].values
Systole = df['Systole'].values
Diastole = df['Diastole'].values
HeartRate = df['HeartRate'].values
BodyTemperature = df['BodyTemperature'].values
BloodSugar = df['BloodSugar'].values
SpO2 = df['SpO2'].values
RespiratoryRate = df['RespiratoryRate'].values


#these are the three values to be calculated
BMI=df['BMI'].values
Deviation=df['Deviation'].values
FitScore=df['FitScore'].values

print(Weight.dtype)

"""### Body Mass Index is calculated and stored in respective list using formula (Weight/Height^2) in kg/m^2"""

#assigning BMI
j=0
for i in range(5):
  #print("Weight="+str(Weight[j]))
  #print("Height="+str(Height[j]))
  BMI[j]= (Weight[j])/((Height[j])*(Height[j]))
  #print(BMI[j])
  j+=1

print(BMI)

"""##Important values used in calculation"""

#normal list contains Initially normal values of all the attributes
#these normal values are safe values
# i.e. if user is in these values, then absolutely fit
#list=[Systole, Diastole, BloodSugar, BMI, SpO2, HeartRate, RespiratoryRate, BodyTemperature]
normal = [120, 80, 95, 21.7, 96, 80, 16, 36.6]
limits = [15, 15, 15, 3.2, 4, 20, 4, 0.6]
critical_min = [50, 30, 70, 13, 19.5, 35, 8, 24]
critical_max = [145, 100, 200, 32, 101, 130, 40, 40]
weights = [0.12, 0.12, 0.2, 0.06, 0.16, 0.14, 0.14, 0.06]
question= [
            [
              "Have you experienced frequent headaches, especially in the morning or on the back of your head?",
              "Do you feel fatigued or have a lack of energy despite getting enough rest?",
              "Have you noticed changes in your vision, such as blurred vision or seeing spots?",
              "Have you felt lightheaded or dizzy?",
              "Are you experiencing any changes in your urinary frequency or patterns?"
            ],
            [
              "Do you have frequent headaches, particularly in the morning?",
              "Have you felt nauseous or experienced blurred vision?",
              "Are you experiencing cold or clammy skin?",
              "Are you having difficulty concentrating or feeling confused?",
              "Have you noticed any changes in your balance or coordination?"
            ],
            [
              "Have you noticed an increase in thirst or are you drinking more fluids than usual?",
              "Are you experiencing frequent urination or have you noticed an increase in the volume of urine?",
              "Have you been feeling fatigued or more tired than usual?",
              "Are you experiencing unexplained weight loss despite a regular diet?",
              "Are you experiencing blurry vision or difficulty focusing?"
            ],
            [
                "Q1",
                "Q2",
                "Q3",
                "Q4",
                "Q5"
            ],
            [
                "Do you feel excessively tired or fatigued even with minimal exertion?",
                "Have you noticed any bluish discoloration of your lips, fingertips, or nail beds?",
                "Do you feel dizzy, lightheaded, or experience episodes of fainting?",
                "Do you have a persistent cough, wheezing, or chest discomfort?",
                "Are you sleeping well, or have you noticed any disturbances in your sleep pattern?"
            ],
            [
                "Q1",
                "Q2",
                "Q3",
                "Q4",
                "Q5"
            ],
            [
                "Q1",
                "Q2",
                "Q3",
                "Q4",
                "Q5"
            ],
            [
                "Q1",
                "Q2",
                "Q3",
                "Q4",
                "Q5"
            ]]

"""#Calculation of error and then Finally calculating FitnessScore

####Error : (Ideal Value - Current Value)*(Slope)

#### Deviation: Weighted sum of all errors

####Fit Score : 1 - Total Deviation
"""

def sol(k):
  ans=0
  solu=0
  i=0
  for i in range(5):
    print(question[k][i])
    ans=int(input())
    solu=solu+ans
  return solu


#function for calculating error
def delta(k, current_value, l):
  error=0
  change=0
  solution=0
  if normal[k]-limits[k] <= current_value <= normal[k]+limits[k] :
    error=0
  elif critical_min[k] <= current_value <= normal[k]-limits[k]:
    solution=sol(k)
    if(solution<3):
      change = (normal[k] - current_value)/l
      normal[k]=normal[k]-change
      critical_min[k]=critical_min[k]-change
      critical_max[k]=critical_max[k]-change

    error = (1/(normal[k]-limits[k] - critical_min[k]))*(normal[k]-limits[k]-current_value)
  elif normal[k]+limits[k] <= current_value <= critical_max[k]:
    solution=sol(k)
    if(solution<3):
      change = (current_value - normal[k])/l
      normal[k]=normal[k]+change
      critical_min[k]=critical_min[k]+change
      critical_max[k]=critical_max[k]+change
    error = (1/(critical_max[k] - normal[k]+limits[k]))*(critical_max[k] - normal[k]+limits[k])
  else:
    error = 1

  return error

#assigning BMI
j=0
#list=[Systole, Diastole, BloodSugar, BMI, SpO2, HeartRate, RespiratoryRate, BodyTemperature]
for i in Height:
  delta_Systole = delta(0, int(Systole[j]), j+1)
  delta_Diastole = delta(1, int(Diastole[j]), j+1)
  delta_BloodSugar = delta(2, int(BloodSugar[j]), j+1)
  delta_BMI = delta(3, int(BMI[j]), j+1)
  delta_SpO2 = delta(4, int(SpO2[j]), j+1)
  delta_HeartRate = delta(5, int(HeartRate[j]), j+1)
  delta_RespiratoryRate = delta(6, int(HeartRate[j]), j+1)
  delta_BodyTemperature = delta(7, int(BodyTemperature[j]), j+1)

  Deviation[j] = (weights[0]*delta_Systole)+(weights[1]*delta_Diastole)+(weights[2]*delta_BloodSugar)+(weights[3]*delta_BMI)+(weights[4]*delta_SpO2)+(weights[5]*delta_HeartRate)+(weights[6]*delta_RespiratoryRate)+(weights[7]*delta_BodyTemperature)

  if(Deviation[j]>1):
    Deviation[j]=Deviation[j]-1
  FitScore[j] = int((1 - Deviation[j])*100)


  j+=1

print(FitScore)

"""# Writing in the Dataset

"""

filename = open("person2.csv",'w')

j=0
for i in Height:
  Rlist1 = str(Weight[j]) + "," + str(Height[j]) + ',' + str(Systole[j]) + ',' + str(Diastole[j]) + ',' + str(HeartRate[j]) + ',' + str(BodyTemperature[j]) +','+str(BloodSugar[j])+ ',' + str(SpO2[j]) + ',' + str(RespiratoryRate[j]) + ',' + str(BMI[j]) + ',' + str(Deviation[j]) + ',' + str(FitScore[j])
  filename.write(Rlist1)
  filename.write("\n")
  filename.flush()

  j+=1
filename.close()

normal

"""These values of normal are changed

i.e. Self adjusted or personalised
"""